### PR TITLE
Feature/sync endpoints

### PR DESCRIPTION
**Pull request by mejamiewilson**
This is how sync endpoints work:
- add `wait` before the endpoint name in the URL, ie `https://endpoint.hoi.io/org-slug/app-slug/wait/my-endpoint`;
- before raising the event attached to that endpoint, endpoint subscribes to `${eventName}::completed` and keeps the connection open
- when executor completes a module run, and the 'synchronous' field is true on the event, it'll raise the completed event on the same correlation id, and sets 'payload' to come from the module's `done` method
- endpoint sees that event and then returns the payload 

broker, model and executor all need to be merged with the same branch name to work 

😄

### CODE REVIEW

**Comment by buildmaster** [comment]
I'm not sure the URL should be varied to make it wait, this really should be a query string parameter or a header. 

The event is still the same event, so the resource address shouldn't change, you're just changing how it loads.

**Comment by buildmaster** [comment]
the rest is awesome, I'll make the change to endpoint to make it a query string param or a header (they'll both do the same)

**Comment by mejamiewilson** [comment]
A couple of things came to mind this morning. 1) should the priority on a waiting request should be higher than a standard endpoint? and 2) i assume you're spinning this up locally to test, see if it works for an error - if the module throws an error, then endpoint.hoi.io should return that error as the payload. I can fix that if it doesn't work currently

**Comment by buildmaster** [comment]
we could possibly use higher than standard. it would make sense

**Pull request merged**
